SRC	= ft_putchar.c ft_swap.c ft_putstr.c ft_strlen.c ft_strcmp.c

SRCS	= $(addprefix ./srcs/, $(SRC))

OBJECTS	= $(SRC: .c=.o)

HEADERS	= ./includes/

NAME	= libft.a

CC	= cc

RM	= rm -f

CFLAGS	= -Wall -Wextra -Werror

